[project]
name = "tempera-midi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mido[ports-rtmidi]",
    "pdoc3>=0.11.6",
    "PySide6>=6.6.0",
    "qasync>=0.27.0",
]
